"""licenca

Revision ID: 252ea9d098a3
Revises: fd35b3d86632
Create Date: 2022-11-26 08:35:14.193949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252ea9d098a3'
down_revision = 'fd35b3d86632'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(), nullable=True),
    sa.Column('chave', sa.String(), nullable=True),
    sa.Column('nota', sa.String(), nullable=True),
    sa.Column('solcompra', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licencas_id'), 'licencas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licencas_id'), table_name='licencas')
    op.drop_table('licencas')
    # ### end Alembic commands ###
