"""patrimonio

Revision ID: fd35b3d86632
Revises: e30ac8bf6af1
Create Date: 2022-11-26 08:34:39.917626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd35b3d86632'
down_revision = 'e30ac8bf6af1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patrimonio', sa.String(), nullable=True),
    sa.Column('depto', sa.String(), nullable=True),
    sa.Column('serivcetag', sa.String(), nullable=True),
    sa.Column('garantia', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patrimonio_id'), 'patrimonio', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patrimonio_id'), table_name='patrimonio')
    op.drop_table('patrimonio')
    # ### end Alembic commands ###
